{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "f8ba1bbb-45a3-4b60-bb4b-7e8ce7bac4d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "###------------------ IMPORT SECTION ------------------###\n",
    "\n",
    "# Import required libraries\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.webdriver.support.ui import Select\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.webdriver.common.action_chains import ActionChains\n",
    "from selenium.common.exceptions import UnexpectedAlertPresentException, TimeoutException\n",
    "from selenium.webdriver.common.alert import Alert\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import time\n",
    "import csv\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "from datetime import datetime\n",
    "import re\n",
    "import json\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "02b7ad19-7703-4173-ae99-f4bf5704e423",
   "metadata": {},
   "outputs": [],
   "source": [
    "###------------------ CONFIGURATION SECTION ------------------###\n",
    "\n",
    "\n",
    "# Setup Chrome WebDriver - Configure Selenium to use Chrome\n",
    "options = Options()\n",
    "# options.add_argument(\"--headless=new\")  # Correct syntax for headless\n",
    "options.add_argument(\"--disable-popup-blocking\")\n",
    "options.add_argument(\"--disable-gpu\")\n",
    "options.add_argument(\"--no-sandbox\")\n",
    "options.add_argument(\"--disable-dev-shm-usage\")\n",
    "options.add_argument(\"--start-maximized\")\n",
    "options.add_argument(\"user-agent=Mozilla/5.0\")\n",
    "\n",
    "# # Optional: Disable image loading (better done via prefs)\n",
    "# prefs = {\"profile.managed_default_content_settings.images\": 2}\n",
    "# options.add_experimental_option(\"prefs\", prefs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "id": "84cff027-6509-4870-b5ab-f599c7b2f2bd",
   "metadata": {},
   "outputs": [],
   "source": [
    "###------------------ VARIABLES SECTION ------------------###\n",
    "\n",
    "today = datetime.today().strftime(\"%d-%m-%Y\")\n",
    "\n",
    "url = \"https://dealers.heromotocorp.com/\"\n",
    "\n",
    "# Store showroom data\"\n",
    "data = []\n",
    "state_cities = {}\n",
    "\n",
    "# Constants\n",
    "MAX_RETRIES = 2  # Number of retries per pincode\n",
    "RESTART_BROWSER_AFTER = 10  # Restart Chrome every N pincodes\n",
    "WAIT_TIME = 10  # Increased explicit wait time\n",
    "DATA_SAVE_INTERVAL = 10  # Save every N pincodes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "id": "49bd38e5-ecda-4d08-9bd7-467da759874c",
   "metadata": {},
   "outputs": [],
   "source": [
    "###------------------ PROCESS SECTION ------------------###\n",
    "\n",
    "# Funtion to start a browser\n",
    "def start_browser():\n",
    "    \"\"\"Starts a new browser session.\"\"\"\n",
    "    driver = webdriver.Chrome(service=Service(), options=options)\n",
    "    driver.maximize_window()\n",
    "    wait = WebDriverWait(driver, WAIT_TIME, poll_frequency=0.5)\n",
    "\n",
    "    driver.get(url)\n",
    "    time.sleep(2)  # Initial load wait\n",
    "    \n",
    "    return driver, wait\n",
    "    \n",
    "# Function to scrape the showrooms from particular city\n",
    "def scrape_dealers(driver, wait, state, city):\n",
    "    \n",
    "    # # Wait until the element is present\n",
    "    # target_element = WebDriverWait(driver, 10).until(\n",
    "    #     EC.presence_of_element_located((By.XPATH, \"/html/body/section[3]/div/div[1]/div[2]/div/div/div[1]/div\"))\n",
    "    # )\n",
    "    \n",
    "    # # Scroll to the element using JavaScript\n",
    "    # driver.execute_script(\"arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center' });\", target_element)\n",
    "    dealers = []\n",
    "\n",
    "    while True:\n",
    "        page_source = driver.page_source\n",
    "        soup = BeautifulSoup(page_source, \"html.parser\")\n",
    "        \n",
    "        container = soup.find(class_=\"dl-branch-container\")\n",
    "        containers = container.find_all(class_=\"dl-branch-container-box\")\n",
    "        showroom_list = []\n",
    "        \n",
    "        if containers[0]:\n",
    "            showroom_list.extend(containers[0].find_all(class_=\"dl-branch\"))\n",
    "        if containers[1]:\n",
    "            showroom_list.extend(containers[1].find_all(class_=\"dl-branch\"))\n",
    "        \n",
    "        for showroom in showroom_list:\n",
    "            # print(showroom)\n",
    "            name = showroom.find(\"div\", class_=\"dl-branch-name\").text.strip()\n",
    "            address = showroom.find(\"div\", class_=\"branch-info dl-branch-address\").text.strip()\n",
    "            phone_div = showroom.find(\"div\", class_=\"branch-info dl-branch-contact\")\n",
    "            phone = phone_div.text.strip() if phone_div else \"\"\n",
    "    \n",
    "            dealers.append([name if name else \"\", address if address else \"\", phone if phone else \"\", city, state])\n",
    "            print(dealers)\n",
    "        # Check for \"Next\" button\n",
    "        try:\n",
    "            next_button = wait.until(EC.element_to_be_clickable((By.XPATH, '//a[contains(@class,\"paginate-buttons next-button\")]')))\n",
    "\n",
    "            # Check if it's disabled or not present\n",
    "            if 'disabled' in next_button.get_attribute(\"class\").lower():\n",
    "                break\n",
    "\n",
    "            # Scroll to and click the next button\n",
    "            driver.execute_script(\"arguments[0].scrollIntoView({block: 'center'});\", next_button)\n",
    "            time.sleep(1)\n",
    "            next_button.click()\n",
    "            time.sleep(2)  # Give it time to load new content\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\"No more pages or error while clicking next: {e}\")\n",
    "            break\n",
    "            \n",
    "    return dealers\n",
    "\n",
    "# Function to select state and city\n",
    "def select_state_city_t(driver, wait):\n",
    "    \n",
    "    page_source = driver.page_source\n",
    "    soup = BeautifulSoup(page_source, \"html.parser\")\n",
    "    containers = soup.find_all(\"div\", class_=\"input-box\")\n",
    "    states_container = containers[0].find(\"div\",class_=\"menu hidden\")\n",
    "    states = [x.text for x in states_container.find_all(\"div\")] \n",
    "    # print(states)\n",
    "\n",
    "    for state in states[10:]:\n",
    "        state_input = driver.find_element(By.XPATH, '//*[@id=\"__nuxt\"]/div/div/div/div[2]/div[1]/div[4]/div[1]/div[1]/input')\n",
    "        state_input.send_keys(Keys.CONTROL + \"a\")\n",
    "        state_input.send_keys(Keys.BACKSPACE)\n",
    "        state_input.send_keys(state)\n",
    "        state_input.send_keys(Keys.ARROW_DOWN)\n",
    "        state_input.send_keys(Keys.ENTER)\n",
    "        time.sleep(1)\n",
    "        \n",
    "        page_source = driver.page_source\n",
    "        soup = BeautifulSoup(page_source, \"html.parser\")\n",
    "        containers = soup.find_all(\"div\", class_=\"input-box\")\n",
    "        cities_container = containers[1].find(\"div\",class_=\"menu hidden\")\n",
    "        cities = [x.text for x in cities_container.find_all(\"div\")]\n",
    "        # print(cities)\n",
    "\n",
    "        for city in cities:\n",
    "\n",
    "            state_input = driver.find_element(By.XPATH, '//*[@id=\"__nuxt\"]/div/div/div/div[2]/div[1]/div[4]/div[1]/div[1]/input')\n",
    "            state_input.send_keys(Keys.CONTROL + \"a\")\n",
    "            state_input.send_keys(Keys.BACKSPACE)\n",
    "            state_input.send_keys(state)\n",
    "            state_input.send_keys(Keys.ARROW_DOWN)\n",
    "            state_input.send_keys(Keys.ENTER)\n",
    "            time.sleep(1)\n",
    "            \n",
    "            city_input = driver.find_element(By.XPATH, '//*[@id=\"__nuxt\"]/div/div/div/div[2]/div[1]/div[4]/div[2]/div[1]/input')\n",
    "            city_input.send_keys(Keys.CONTROL + \"a\")\n",
    "            city_input.send_keys(Keys.BACKSPACE)\n",
    "            city_input.send_keys(city)\n",
    "            city_input.send_keys(Keys.ARROW_DOWN)\n",
    "            city_input.send_keys(Keys.ENTER)\n",
    "            time.sleep(1)\n",
    "\n",
    "            search_button = driver.find_element(By.XPATH, '//*[@id=\"__nuxt\"]/div/div/div/div[2]/div[1]/div[4]/div[4]/button')\n",
    "            # Scroll to and click the search button\n",
    "            # driver.execute_script(\"arguments[0].scrollIntoView({block: 'center'});\", search_button)\n",
    "            driver.execute_script(\"\"\"\n",
    "                            arguments[0].scrollIntoView({block: 'center'});\n",
    "                            arguments[0].click();\n",
    "                        \"\"\", search_button)\n",
    "            # search_button.click()\n",
    "            time.sleep(2)\n",
    "            dealers = scrape_dealers(driver, wait, state, city)\n",
    "            data.extend(dealers)\n",
    "    \n",
    "# Function to select state and city\n",
    "def select_state_city(driver, wait):\n",
    "    # Wait until the dropdown is present\n",
    "    wait.until(EC.presence_of_element_located((By.ID, \"OutletState\")))\n",
    "    \n",
    "    # Get the Select object from the state dropdown\n",
    "    state_dropdown_el = driver.find_element(By.ID, \"OutletState\")\n",
    "    state_dropdown = Select(state_dropdown_el)\n",
    "\n",
    "    for index in range(len(state_dropdown.options)):\n",
    "        retry_count = 0\n",
    "        # scrape_dealers(driver, wait, city)\n",
    "        while retry_count < MAX_RETRIES:\n",
    "\n",
    "            try:\n",
    "                # Wait until the element is present\n",
    "                target_element = WebDriverWait(driver, 10).until(\n",
    "                    EC.presence_of_element_located((By.XPATH, \"/html/body/section[2]/div[2]\"))\n",
    "                )\n",
    "                \n",
    "                # Scroll to the element using JavaScript\n",
    "                driver.execute_script(\"arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center' });\", target_element)\n",
    "                \n",
    "                # Re-fetch the dropdown and its options on every iteration\n",
    "                state_dropdown_el = driver.find_element(By.ID, \"OutletState\")\n",
    "                state_dropdown = Select(state_dropdown_el)\n",
    "        \n",
    "                state_option = state_dropdown.options[index]\n",
    "                state_value = state_option.text\n",
    "                # Defensive try-except in case of a rare race condition\n",
    "                try:\n",
    "                    state = state_option.get_attribute(\"value\")\n",
    "                except StaleElementReferenceException:\n",
    "                    print(\"Stale element, re-fetching and retrying\")\n",
    "                    continue\n",
    "        \n",
    "                if not state:\n",
    "                    continue\n",
    "        \n",
    "                print(\"Selecting state:\", state)\n",
    "                state_dropdown.select_by_value(state)\n",
    "        \n",
    "                # wait or do actions here (like triggering city loading, etc.)\n",
    "                time.sleep(2)  # Or use a better WebDriverWait\n",
    "        \n",
    "                \n",
    "                # # Wait for the city dropdown to update\n",
    "                wait.until(EC.presence_of_element_located((By.ID, \"OutletCity\")))\n",
    "        \n",
    "                # Grab city dropdown options\n",
    "                city_dropdown = Select(wait.until(EC.presence_of_element_located((By.ID, \"OutletCity\"))))\n",
    "                for city_index in range(len(city_dropdown.options)):\n",
    "    \n",
    "                    retry_count_city = 0\n",
    "                    # scrape_dealers(driver, wait, city)\n",
    "                    while retry_count_city < MAX_RETRIES:\n",
    "                        try:\n",
    "                            # Wait until the element is present\n",
    "                            target_element = WebDriverWait(driver, 10).until(\n",
    "                                EC.presence_of_element_located((By.XPATH, \"/html/body/section[2]/div[2]\"))\n",
    "                            )\n",
    "                            # Scroll to the element using JavaScript\n",
    "                            driver.execute_script(\"arguments[0].scrollIntoView({ behavior: 'smooth', block: 'center' });\", target_element)\n",
    "                            \n",
    "                            # Re-fetch the city dropdown and its options on every iteration\n",
    "                            city_dropdown = Select(wait.until(EC.presence_of_element_located((By.ID, \"OutletCity\"))))\n",
    "                            \n",
    "                            city_option = city_dropdown.options[city_index]\n",
    "                            city_value = city_option.text\n",
    "                            city = city_option.get_attribute(\"value\")\n",
    "                            \n",
    "                            if not city:\n",
    "                                continue\n",
    "                            print(\"Selecting city:\", city)\n",
    "                            city_dropdown.select_by_value(city)\n",
    "                            \n",
    "                            # driver.execute_script(\"window.scrollTo(0,500);\")\n",
    "                            submit = wait.until(EC.presence_of_element_located((By.XPATH, '//*[@id=\"OutletStoreLocatorSearchForm\"]/div/div[2]/div[2]/input')))\n",
    "                            submit.click()\n",
    "                            time.sleep(3)\n",
    "                            dealers = scrape_dealers(driver, wait, state_value, city_value)\n",
    "                            data.extend(dealers)\n",
    "                            break\n",
    "                            \n",
    "                        except Exception as e:\n",
    "                            retry_count_city += 1\n",
    "                            if retry_count_city == MAX_RETRIES:\n",
    "                                break\n",
    "                            if \"TimeoutException\" in e:\n",
    "                                driver.quit()\n",
    "                                driver, wait = start_browser()\n",
    "                                break\n",
    "                            time.sleep(3)\n",
    "                                \n",
    "            except:\n",
    "                retry_count += 1\n",
    "                if retry_count == MAX_RETRIES:\n",
    "                    break\n",
    "                time.sleep(3)\n",
    "# Function to run the process step by step\n",
    "def main():\n",
    "    driver, wait = start_browser()\n",
    "    \n",
    "    select_state_city_t(driver,wait)\n",
    "\n",
    "    driver.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8ddcd892-a415-425e-af9a-392ec0a0f061",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat'], ['Shradha Motors - Hero MotoCorp - Ambawadi', 'Upnishad Building, Manekbaug Hall Road, Ambawadi, ahmedabad , gujarat - 380015', '9289922563', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat'], ['Shradha Motors - Hero MotoCorp - Ambawadi', 'Upnishad Building, Manekbaug Hall Road, Ambawadi, ahmedabad , gujarat - 380015', '9289922563', 'Ahmedabad', 'Gujarat'], ['Buy Now - Hero MotoCorp - Naranpura', 'No G/5, Ground Floor, Akash 3, BRTS Road, Naranpura, ahmedabad , gujarat - 380013', '9825617183', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat'], ['Shradha Motors - Hero MotoCorp - Ambawadi', 'Upnishad Building, Manekbaug Hall Road, Ambawadi, ahmedabad , gujarat - 380015', '9289922563', 'Ahmedabad', 'Gujarat'], ['Buy Now - Hero MotoCorp - Naranpura', 'No G/5, Ground Floor, Akash 3, BRTS Road, Naranpura, ahmedabad , gujarat - 380013', '9825617183', 'Ahmedabad', 'Gujarat'], ['Shradha Automobiles - Hero MotoCorp - Vande Matram City', 'GF 2/102/201, NY Square, PN 253/4, Chainpur Gota, Vande Matram City, ahmedabad , gujarat - 382470', '9289922209', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat'], ['Shradha Motors - Hero MotoCorp - Ambawadi', 'Upnishad Building, Manekbaug Hall Road, Ambawadi, ahmedabad , gujarat - 380015', '9289922563', 'Ahmedabad', 'Gujarat'], ['Buy Now - Hero MotoCorp - Naranpura', 'No G/5, Ground Floor, Akash 3, BRTS Road, Naranpura, ahmedabad , gujarat - 380013', '9825617183', 'Ahmedabad', 'Gujarat'], ['Shradha Automobiles - Hero MotoCorp - Vande Matram City', 'GF 2/102/201, NY Square, PN 253/4, Chainpur Gota, Vande Matram City, ahmedabad , gujarat - 382470', '9289922209', 'Ahmedabad', 'Gujarat'], ['Shree Bali Auto Services - Hero MotoCorp - Odhav', 'Ground Floor, Odhav, ahmedabad , gujarat - 382415', '09289923881', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat'], ['Shradha Motors - Hero MotoCorp - Ambawadi', 'Upnishad Building, Manekbaug Hall Road, Ambawadi, ahmedabad , gujarat - 380015', '9289922563', 'Ahmedabad', 'Gujarat'], ['Buy Now - Hero MotoCorp - Naranpura', 'No G/5, Ground Floor, Akash 3, BRTS Road, Naranpura, ahmedabad , gujarat - 380013', '9825617183', 'Ahmedabad', 'Gujarat'], ['Shradha Automobiles - Hero MotoCorp - Vande Matram City', 'GF 2/102/201, NY Square, PN 253/4, Chainpur Gota, Vande Matram City, ahmedabad , gujarat - 382470', '9289922209', 'Ahmedabad', 'Gujarat'], ['Shree Bali Auto Services - Hero MotoCorp - Odhav', 'Ground Floor, Odhav, ahmedabad , gujarat - 382415', '09289923881', 'Ahmedabad', 'Gujarat'], ['Gautam Bikes - Hero MotoCorp - Gandhinagar', 'No 14, Sopan Appartments, Chandkheda, Gandhinagar, ahmedabad , gujarat - 382424', '9824374675', 'Ahmedabad', 'Gujarat']]\n",
      "[['PREMIA - Ahmedabad - M/S Raj Vehicles - Hero MotoCorp - Sola', 'Shop No 1-5, Sola Over Bridge, Sarkhej - Gandhinagar Highway, Shiv Shakti Nagar, Sola, ahmedabad , gujarat - 380060', '09898031625', 'Ahmedabad', 'Gujarat'], ['Rohan Motors - Hero MotoCorp - Vitthalapur', 'Shop No 1 to 4, Aaj Business Hub, Vitthalapur, ahmedabad , gujarat - 382120', '9925506434', 'Ahmedabad', 'Gujarat'], ['Chiraniya Autohaus - Hero Motocorp - Old Wadaj', 'No 5, B/H 132, Subhash Bridge, RTO Circle, 132 Feet Ring Road, Old Wadaj, ahmedabad , gujarat - 380027', '09289235287', 'Ahmedabad', 'Gujarat'], ['Durga Auto - Hero MotoCorp - Narolgam', 'Plot No 7, Bhamariya Kuwo, Gurukrupa Estate, Narolgam, ahmedabad , gujarat - 382405', '09998940583', 'Ahmedabad', 'Gujarat'], ['Bikes Auto - Hero MotoCorp - Navrangpura', 'Drive In Rd, Navrangpura, ahmedabad , gujarat - 380009', '9289922253', 'Ahmedabad', 'Gujarat'], ['M/S Star Automobiles - Hero Motocorp - Dholka', 'Sy 778/1 & 2, Dholka Bavala Road, Balas Chokadi, Dholka, ahmedabad , gujarat - 382225', '9925022716', 'Ahmedabad', 'Gujarat'], ['M/S Raj Vehicles - Hero Motocorp - Ghatlodia', 'No 407, FP No 10, Sardar Patel Ring Road, Bopal Circle, Ambali, Ghatlodia, ahmedabad , gujarat - 380058', '7486003790', 'Ahmedabad', 'Gujarat'], ['M Raj Automobiles - Hero MotoCorp - Hansalpur', 'Malwan Chowkdi, Hansalpur, ahmedabad , gujarat - 382150', '09289924084', 'Ahmedabad', 'Gujarat'], ['Petal Automotion - Hero MotoCorp - Naroda', 'Shop No 4, Ground Flr, Kayakalp Building, Naroda, ahmedabad , gujarat - 382330', '9289923135', 'Ahmedabad', 'Gujarat'], ['Rajdeep Automobiles - Hero MotoCorp - Amraiwadi', 'NH 8, Amraiwadi, ahmedabad , gujarat - 380026', '9289922511', 'Ahmedabad', 'Gujarat'], ['Keshav Motors - Hero MotoCorp - Nikol', 'S No 33/5, SP Ring Road, Nikol, ahmedabad , gujarat - 382350', '9289922822', 'Ahmedabad', 'Gujarat'], ['Karnavati Bikes - Hero MotoCorp - Bapunagar', '20/23, Anupam Colony, LBS Rd, Bapunagar, ahmedabad , gujarat - 380024', '9289922607', 'Ahmedabad', 'Gujarat'], ['Shradha Motors - Hero MotoCorp - Ambawadi', 'Upnishad Building, Manekbaug Hall Road, Ambawadi, ahmedabad , gujarat - 380015', '9289922563', 'Ahmedabad', 'Gujarat'], ['Buy Now - Hero MotoCorp - Naranpura', 'No G/5, Ground Floor, Akash 3, BRTS Road, Naranpura, ahmedabad , gujarat - 380013', '9825617183', 'Ahmedabad', 'Gujarat'], ['Shradha Automobiles - Hero MotoCorp - Vande Matram City', 'GF 2/102/201, NY Square, PN 253/4, Chainpur Gota, Vande Matram City, ahmedabad , gujarat - 382470', '9289922209', 'Ahmedabad', 'Gujarat'], ['Shree Bali Auto Services - Hero MotoCorp - Odhav', 'Ground Floor, Odhav, ahmedabad , gujarat - 382415', '09289923881', 'Ahmedabad', 'Gujarat'], ['Gautam Bikes - Hero MotoCorp - Gandhinagar', 'No 14, Sopan Appartments, Chandkheda, Gandhinagar, ahmedabad , gujarat - 382424', '9824374675', 'Ahmedabad', 'Gujarat'], ['Jay Bhole Auto - Hero MotoCorp - Kuha', 'Block Survey No 2239, Daskroi, Kuha, ahmedabad , gujarat - 382433', '09974865800', 'Ahmedabad', 'Gujarat']]\n",
      "No more pages or error while clicking next: Message: \n",
      "Stacktrace:\n",
      "Symbols not available. Dumping unresolved backtrace:\n",
      "\t0x7ff76161a535\n",
      "\t0x7ff76161a590\n",
      "\t0x7ff7613c10bd\n",
      "\t0x7ff76141c48e\n",
      "\t0x7ff76141c79c\n",
      "\t0x7ff76146d3a7\n",
      "\t0x7ff761469ef5\n",
      "\t0x7ff76140cc9c\n",
      "\t0x7ff76140dbe3\n",
      "\t0x7ff7618f7b60\n",
      "\t0x7ff7618f1f5d\n",
      "\t0x7ff76191311a\n",
      "\t0x7ff7616360a5\n",
      "\t0x7ff76163e73c\n",
      "\t0x7ff761623844\n",
      "\t0x7ff7616239f6\n",
      "\t0x7ff761609a07\n",
      "\t0x7ffac5dce8d7\n",
      "\t0x7ffac6f6c53c\n",
      "\n",
      "[['Accurate Auto Agency - Hero Motocorp - Mahuva Road', 'No 70, Amreli, Mahuva Road, amreli , gujarat - 364515', '09289924085', 'Amreli', 'Gujarat']]\n",
      "[['Accurate Auto Agency - Hero Motocorp - Mahuva Road', 'No 70, Amreli, Mahuva Road, amreli , gujarat - 364515', '09289924085', 'Amreli', 'Gujarat'], ['Navnit Auto Centre - Hero MotoCorp - Station Road', 'Ground Floor, Station Road, amreli , gujarat - 365601', '9289922254', 'Amreli', 'Gujarat']]\n",
      "No more pages or error while clicking next: Message: \n",
      "Stacktrace:\n",
      "Symbols not available. Dumping unresolved backtrace:\n",
      "\t0x7ff76161a535\n",
      "\t0x7ff76161a590\n",
      "\t0x7ff7613c10bd\n",
      "\t0x7ff76141c48e\n",
      "\t0x7ff76141c79c\n",
      "\t0x7ff76146d3a7\n",
      "\t0x7ff761469ef5\n",
      "\t0x7ff76140cc9c\n",
      "\t0x7ff76140dbe3\n",
      "\t0x7ff7618f7b60\n",
      "\t0x7ff7618f1f5d\n",
      "\t0x7ff76191311a\n",
      "\t0x7ff7616360a5\n",
      "\t0x7ff76163e73c\n",
      "\t0x7ff761623844\n",
      "\t0x7ff7616239f6\n",
      "\t0x7ff761609a07\n",
      "\t0x7ffac5dce8d7\n",
      "\t0x7ffac6f6c53c\n",
      "\n",
      "[['M/S Bikes Zone - Hero MotoCorp - Mankol', 'Property No 2052, Mankol, sanand , gujarat - 382110', '09974135915', 'Anand', 'Gujarat']]\n",
      "[['M/S Bikes Zone - Hero MotoCorp - Mankol', 'Property No 2052, Mankol, sanand , gujarat - 382110', '09974135915', 'Anand', 'Gujarat'], ['Bikes Automotive - Hero MotoCorp - Sanand', 'Plot No 19/6, Central Park, Viramgam Highway, Sanand, sanand , gujarat - 382110', '9289923089', 'Anand', 'Gujarat']]\n",
      "No more pages or error while clicking next: Message: \n",
      "Stacktrace:\n",
      "Symbols not available. Dumping unresolved backtrace:\n",
      "\t0x7ff76161a535\n",
      "\t0x7ff76161a590\n",
      "\t0x7ff7613c10bd\n",
      "\t0x7ff76141c48e\n",
      "\t0x7ff76141c79c\n",
      "\t0x7ff76146d3a7\n",
      "\t0x7ff761469ef5\n",
      "\t0x7ff76140cc9c\n",
      "\t0x7ff76140dbe3\n",
      "\t0x7ff7618f7b60\n",
      "\t0x7ff7618f1f5d\n",
      "\t0x7ff76191311a\n",
      "\t0x7ff7616360a5\n",
      "\t0x7ff76163e73c\n",
      "\t0x7ff761623844\n",
      "\t0x7ff7616239f6\n",
      "\t0x7ff761609a07\n",
      "\t0x7ffac5dce8d7\n",
      "\t0x7ffac6f6c53c\n",
      "\n",
      "[['Anas Motors PVT LTD - Hero MotoCorp - ONGC Road', 'Ground Floor, Teen Rasta Circle, ONGC Road, ankleshwar , gujarat - 393001', '9289922241', 'Ankleshwar', 'Gujarat']]\n",
      "No more pages or error while clicking next: Message: \n",
      "Stacktrace:\n",
      "Symbols not available. Dumping unresolved backtrace:\n",
      "\t0x7ff76161a535\n",
      "\t0x7ff76161a590\n",
      "\t0x7ff7613c10bd\n",
      "\t0x7ff76141c48e\n",
      "\t0x7ff76141c79c\n",
      "\t0x7ff76146d3a7\n",
      "\t0x7ff761469ef5\n",
      "\t0x7ff76140cc9c\n",
      "\t0x7ff76140dbe3\n",
      "\t0x7ff7618f7b60\n",
      "\t0x7ff7618f1f5d\n",
      "\t0x7ff76191311a\n",
      "\t0x7ff7616360a5\n",
      "\t0x7ff76163e73c\n",
      "\t0x7ff761623844\n",
      "\t0x7ff7616239f6\n",
      "\t0x7ff761609a07\n",
      "\t0x7ffac5dce8d7\n",
      "\t0x7ffac6f6c53c\n",
      "\n",
      "[['Pavan Auto Agency - Hero MotoCorp - Ganesh Pur', 'Ground Floor, Shamlaji Road, Ganesh Pur, aravalli , gujarat - 383315', '9289922826', 'Aravalli', 'Gujarat']]\n",
      "[['Pavan Auto Agency - Hero MotoCorp - Ganesh Pur', 'Ground Floor, Shamlaji Road, Ganesh Pur, aravalli , gujarat - 383315', '9289922826', 'Aravalli', 'Gujarat'], ['Shree Ganesh Auto Agency - Hero MotoCorp - Bayad', 'Survey No 874, 2/4, Ravi Complex, Bayad, aravalli , gujarat - 383325', '09289923985', 'Aravalli', 'Gujarat']]\n",
      "No more pages or error while clicking next: Message: \n",
      "Stacktrace:\n",
      "Symbols not available. Dumping unresolved backtrace:\n",
      "\t0x7ff76161a535\n",
      "\t0x7ff76161a590\n",
      "\t0x7ff7613c10bd\n",
      "\t0x7ff76141c48e\n",
      "\t0x7ff76141c79c\n",
      "\t0x7ff76146d3a7\n",
      "\t0x7ff761469ef5\n",
      "\t0x7ff76140cc9c\n",
      "\t0x7ff76140dbe3\n",
      "\t0x7ff7618f7b60\n",
      "\t0x7ff7618f1f5d\n",
      "\t0x7ff76191311a\n",
      "\t0x7ff7616360a5\n",
      "\t0x7ff76163e73c\n",
      "\t0x7ff761623844\n",
      "\t0x7ff7616239f6\n",
      "\t0x7ff761609a07\n",
      "\t0x7ffac5dce8d7\n",
      "\t0x7ffac6f6c53c\n",
      "\n",
      "[['Vamdote Automobiles - Hero MotoCorp - Nandida Char Rasta', 'No 1241, Nandida Char Rasta, bardoli , gujarat - 394601', '9289923136', 'Bardoli', 'Gujarat']]\n"
     ]
    }
   ],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "    \n",
    "    df = pd.DataFrame(data, columns=[\"Showroom Name\", \"Address\", \"Phone\", \"City\", \"State\"]).drop_duplicates()\n",
    "        \n",
    "    # Save updated file\n",
    "    filename = f\"hero_showrooms_{today}.csv\"\n",
    "    df.to_csv(filename, index=False)\n",
    "    print(f\"Done! ✅ Updated DataFrame saved as {filename}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0f2a230-a36f-4c11-802a-d9950957f0f9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

