name: Run Hero Motocorp Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt

      - name: Run script
        run: |
          cd Hero_Motocorp
          python Hero_Motocorp.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data-Hero Motocorp
          path: Hero_Motocorp/hero_showrooms_*.csv
